// GENERATED by scripts/media/optimize.ts - do not edit by hand. Re-run `npm run media:optimize`.
import type { ImageAsset, VideoAsset } from '../../components/media/types';

import problem_1400_avif from './problem-1400.avif';
import problem_1400_webp from './problem-1400.webp';
import problem_800_avif from './problem-800.avif';
import problem_800_webp from './problem-800.webp';
import problem_jpg from './problem-1400.jpg';
import audienceFounders_900_avif from './audience-founders-900.avif';
import audienceFounders_900_webp from './audience-founders-900.webp';
import audienceFounders_500_avif from './audience-founders-500.avif';
import audienceFounders_500_webp from './audience-founders-500.webp';
import audienceFounders_jpg from './audience-founders-900.jpg';
import audienceAgencies_900_avif from './audience-agencies-900.avif';
import audienceAgencies_900_webp from './audience-agencies-900.webp';
import audienceAgencies_500_avif from './audience-agencies-500.avif';
import audienceAgencies_500_webp from './audience-agencies-500.webp';
import audienceAgencies_jpg from './audience-agencies-900.jpg';
import audienceGrowth_900_avif from './audience-growth-900.avif';
import audienceGrowth_900_webp from './audience-growth-900.webp';
import audienceGrowth_500_avif from './audience-growth-500.avif';
import audienceGrowth_500_webp from './audience-growth-500.webp';
import audienceGrowth_jpg from './audience-growth-900.jpg';
import about_1400_avif from './about-1400.avif';
import about_1400_webp from './about-1400.webp';
import about_800_avif from './about-800.avif';
import about_800_webp from './about-800.webp';
import about_jpg from './about-1400.jpg';
import features_2000_avif from './features-2000.avif';
import features_2000_webp from './features-2000.webp';
import features_1000_avif from './features-1000.avif';
import features_1000_webp from './features-1000.webp';
import features_jpg from './features-2000.jpg';
import shotAngleminer_1280_avif from './shot-angleminer-1280.avif';
import shotAngleminer_1280_webp from './shot-angleminer-1280.webp';
import shotAngleminer_800_avif from './shot-angleminer-800.avif';
import shotAngleminer_800_webp from './shot-angleminer-800.webp';
import shotAngleminer_jpg from './shot-angleminer-1280.jpg';
import shotTestlab_1280_avif from './shot-testlab-1280.avif';
import shotTestlab_1280_webp from './shot-testlab-1280.webp';
import shotTestlab_800_avif from './shot-testlab-800.avif';
import shotTestlab_800_webp from './shot-testlab-800.webp';
import shotTestlab_jpg from './shot-testlab-1280.jpg';
import shotDoctor_1280_avif from './shot-doctor-1280.avif';
import shotDoctor_1280_webp from './shot-doctor-1280.webp';
import shotDoctor_800_avif from './shot-doctor-800.avif';
import shotDoctor_800_webp from './shot-doctor-800.webp';
import shotDoctor_jpg from './shot-doctor-1280.jpg';
import hero_mp4 from './hero.mp4';
import hero_720 from './hero-720.mp4';
import hero_poster from './hero-poster.jpg';
import hero_posterWebp from './hero-poster.webp';

export const problem: ImageAsset = {
  alt: "Scattered red points dissolving into static, with one coherent red line cutting through", width: 1400, height: 1050,
  sources: [{ type: 'image/avif', srcSet: `${problem_1400_avif} 1400w, ${problem_800_avif} 800w` }, { type: 'image/webp', srcSet: `${problem_1400_webp} 1400w, ${problem_800_webp} 800w` }],
  fallback: problem_jpg,
};
export const audienceFounders: ImageAsset = {
  alt: "", width: 900, height: 506,
  sources: [{ type: 'image/avif', srcSet: `${audienceFounders_900_avif} 900w, ${audienceFounders_500_avif} 500w` }, { type: 'image/webp', srcSet: `${audienceFounders_900_webp} 900w, ${audienceFounders_500_webp} 500w` }],
  fallback: audienceFounders_jpg,
};
export const audienceAgencies: ImageAsset = {
  alt: "", width: 900, height: 506,
  sources: [{ type: 'image/avif', srcSet: `${audienceAgencies_900_avif} 900w, ${audienceAgencies_500_avif} 500w` }, { type: 'image/webp', srcSet: `${audienceAgencies_900_webp} 900w, ${audienceAgencies_500_webp} 500w` }],
  fallback: audienceAgencies_jpg,
};
export const audienceGrowth: ImageAsset = {
  alt: "", width: 900, height: 507,
  sources: [{ type: 'image/avif', srcSet: `${audienceGrowth_900_avif} 900w, ${audienceGrowth_500_avif} 500w` }, { type: 'image/webp', srcSet: `${audienceGrowth_900_webp} 900w, ${audienceGrowth_500_webp} 500w` }],
  fallback: audienceGrowth_jpg,
};
export const about: ImageAsset = {
  alt: "Dark fog clearing to reveal a chrome instrument with a single red indicator", width: 1400, height: 933,
  sources: [{ type: 'image/avif', srcSet: `${about_1400_avif} 1400w, ${about_800_avif} 800w` }, { type: 'image/webp', srcSet: `${about_1400_webp} 1400w, ${about_800_webp} 800w` }],
  fallback: about_jpg,
};
export const features: ImageAsset = {
  alt: "A wide bench of matte black instruments with thin red indicator lines", width: 2000, height: 857,
  sources: [{ type: 'image/avif', srcSet: `${features_2000_avif} 2000w, ${features_1000_avif} 1000w` }, { type: 'image/webp', srcSet: `${features_2000_webp} 2000w, ${features_1000_webp} 1000w` }],
  fallback: features_jpg,
};
export const shotAngleminer: ImageAsset = {
  alt: "AngleMiner X results showing generated marketing angles", width: 1280, height: 960,
  sources: [{ type: 'image/avif', srcSet: `${shotAngleminer_1280_avif} 1280w, ${shotAngleminer_800_avif} 800w` }, { type: 'image/webp', srcSet: `${shotAngleminer_1280_webp} 1280w, ${shotAngleminer_800_webp} 800w` }],
  fallback: shotAngleminer_jpg,
};
export const shotTestlab: ImageAsset = {
  alt: "TestLab Pro comparing two variants with predicted scores", width: 1280, height: 960,
  sources: [{ type: 'image/avif', srcSet: `${shotTestlab_1280_avif} 1280w, ${shotTestlab_800_avif} 800w` }, { type: 'image/webp', srcSet: `${shotTestlab_1280_webp} 1280w, ${shotTestlab_800_webp} 800w` }],
  fallback: shotTestlab_jpg,
};
export const shotDoctor: ImageAsset = {
  alt: "Conversion Doctor diagnosis listing blockers and prescriptions", width: 1280, height: 960,
  sources: [{ type: 'image/avif', srcSet: `${shotDoctor_1280_avif} 1280w, ${shotDoctor_800_avif} 800w` }, { type: 'image/webp', srcSet: `${shotDoctor_1280_webp} 1280w, ${shotDoctor_800_webp} 800w` }],
  fallback: shotDoctor_jpg,
};
export const hero: VideoAsset = {
  alt: "", width: 1920, height: 1080,
  mp4: hero_mp4, mp4Mobile: hero_720, poster: hero_poster, posterWebp: hero_posterWebp,
};
