// Reports — unified reporting surface (Master Wiring: one reporting engine). Lists the saved
// reports visible in the user's ACTIVE scope (personal by default; team/client/enterprise when
// scoped via the ScopeSwitcher). Read-only here; reports are generated by the analysis/org flows.

import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Report } from '../types';
import { useAuth } from '../context/AuthContext';
import { useScope } from '../context/ScopeContext';
import { getReportsForScope } from '../services/persistenceService';
import { PageHeader, Card, EmptyState, LoadingState } from '../components/UI';

const Reports: React.FC = () => {
  const { user } = useAuth();
  const { scope } = useScope();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    if (!user) return;
    setLoading(true);
    getReportsForScope(user.uid, scope)
      .then(rows => { if (active) setReports(rows); })
      .catch(console.error)
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [user, scope]);

  const scopeLabel =
    scope.level === 'personal' ? 'Personal'
    : scope.level === 'team' ? 'Team Workspace'
    : scope.level === 'client' ? 'Client'
    : 'Enterprise';

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle={`Saved intelligence reports in your ${scopeLabel} scope. Generate new ones from any analysis tool.`}
      />

      {loading ? (
        <LoadingState message="Loading Reports..." />
      ) : reports.length === 0 ? (
        <Card>
          <EmptyState
            message="No reports yet"
            submessage="Run an analysis and save it as a report to start building your reporting library. Reports you generate in this scope will appear here."
          />
          <div className="flex justify-center">
            <Link
              to="/"
              className="text-[10px] font-bold text-[#FF0000] uppercase tracking-widest hover:opacity-60 transition-opacity border-b border-[#FF0000]/20 pb-1"
            >
              Run your first analysis →
            </Link>
          </div>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {reports.map((r) => {
            const date = r.created_at ? new Date(r.created_at) : null;
            return (
              <Card key={r.id} accent className="!p-8">
                <p className="text-[9px] font-bold text-gray-400 uppercase tracking-[0.3em] mb-3">
                  {r.report_type || 'Report'}
                  {date && <> • {date.toLocaleDateString()}</>}
                </p>
                <h3 className="text-lg font-bold text-[#0B0B0B] tracking-tight leading-snug">
                  {r.title || 'Untitled Report'}
                </h3>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Reports;
