import React from 'react';
import type { ImageAsset } from './types';

interface PictureProps {
  asset: ImageAsset;
  /** Rendered width hint for the browser's srcset selection, e.g. "(min-width: 1024px) 50vw, 100vw". */
  sizes?: string;
  /** Above-the-fold images should be eager; everything else lazy (default). */
  priority?: boolean;
  className?: string;
  imgClassName?: string;
}

/**
 * Responsive <picture>: avif -> webp -> jpg, explicit width/height so the layout never shifts while it loads.
 * Assets come from assets/media/index.ts (generated by `npm run media:optimize`).
 */
const Picture: React.FC<PictureProps> = ({ asset, sizes = '100vw', priority = false, className = '', imgClassName = '' }) => (
  <picture className={`block ${className}`}>
    {asset.sources.map((s) => (
      <source key={s.type} type={s.type} srcSet={s.srcSet} sizes={sizes} />
    ))}
    <img
      src={asset.fallback}
      alt={asset.alt}
      width={asset.width}
      height={asset.height}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      fetchPriority={priority ? 'high' : 'auto'}
      className={`block w-full h-auto ${imgClassName}`}
    />
  </picture>
);

export default Picture;
